# TODO: zsh color scheme
# TODO: split for optimization?

source ~/.profile
# === Antigen ===
source $DOT_DIR/shell/antigen

antigen use oh-my-zsh
antigen bundle zsh-users/zsh-syntax-highlighting
antigen apply

# === Source ===
source $DOT_DIR/shell/var
source $DOT_DIR/shell/alias

# fasd init
eval "$(fasd --init auto)"

# === Prompt ===
local return_code="%(?..%{$fg[red]%}%? ↵%{$reset_color%})"
local user_host='%{$fg[green]%}%n@%m%{$reset_color%}'
local current_dir='%{$fg[blue]%}%~%{$reset_color%}'
local git_branch='$(git_prompt_info)%{$reset_color%}'

PROMPT="%B[%b${user_host}:${current_dir}${git_branch}%B]%b
$ "

ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg[yellow]%} ‹"
ZSH_THEME_GIT_PROMPT_SUFFIX="›%{$reset_color%}"

# === Options ===
export LSCOLORS=exGxcxdxbxegedabagacad
export EDITOR=vim
set -o vi

setopt CORRECT
setopt HISTIGNOREDUPS
setopt EXTENDEDHISTORY
setopt APPENDHISTORY

HISTSIZE=10000
SAVEHIST=10000
HISTFILE=$DOT_DIR/shell/.zsh_history
ZDOTDIR=$DOT_DIR/shell

# === Source specific files ===
source $DOT_DIR/shell/*.zsh
