#!/bin/sh 

#TODO:
# dotfile clean
# dotfile update

# maybe allow overriding this with parameter
echo "export DOT_DIR=~/.dotfiles" > ~/.profile
source ~/.profile

mv $(dirname $0) $DOT_DIR > /dev/null 2>&1
cd $DOT_DIR

echo " --- configuring shell ---"
if [ ! -f $HOME/.bash_profile ]; then
	touch $HOME/.bash_profile
fi
echo "source $DOT_DIR/shell/bashrc" > $HOME/.bash_profile
ln -sf $DOT_DIR/shell/bashrc $HOME/.bashrc
ln -sf $DOT_DIR/shell/zshrc $HOME/.zshrc

echo " --- configuring git ---"
git config --global --add user.name "Austin Kim"
git config --global --add core.excludesfile $DOT_DIR/gitignore_global
git config --global --add include.path $DOT_DIR/gitconfig_global

echo " --- configuring vim ---"
ln -sf $DOT_DIR/vimrc $HOME/.vimrc
mkdir -p ~/.vim/autoload
mkdir -p ~/.vim/colors
ln -sf $DOT_DIR/vim/autoload/* $HOME/.vim/autoload/
ln -sf $DOT_DIR/vim/colors/* $HOME/.vim/colors/

echo " --- done ---"
