#!/bin/sh

#TODO:
# dotfile clean
# dotfile update
# configure nvim

# maybe allow overriding this with parameter
DOT_DIR="$HOME/.dotfiles"

SHELLS="bash zsh"

mv $(dirname $0) $DOT_DIR/.. > /dev/null 2>&1
cd $DOT_DIR

mkdir -p $HOME/.shell
if [ ! -f $HOME/.shell/profile ] ; then
  echo "--- creating profile ---"
  cat "export DOT_DIR=$DOT_DIR" > $HOME/.shell/profile
fi

echo " --- configuring shell ---"

# if shell files exist already, move them and create new symlinks
# doesn't replace existing symlinks
for shell in $SHELLS; do
  if [ ! -h $HOME/.${shell}rc ]; then
    if [ -f $HOME/.${shell}rc ]; then
      echo ".${shell}rc exists - moving to .${shell}rc_original"
      mv $HOME/.${shell}rc $HOME/.${shell}rc_original
    fi
  fi
  ln -sf $DOT_DIR/${shell}/${shell}rc $HOME/.${shell}rc
  echo "created symlink for ${shell}rc"
done

#override bash_profile
ln -sf $DOT_DIR/bash/bash_profile $HOME/.bash_profile
echo "created symlink for bash_profile"

echo " --- configuring git ---"
git config --global --add user.name "Austin Kim"
git config --global --add core.excludesfile $DOT_DIR/git/gitignore_global
git config --global --add include.path $DOT_DIR/git/gitconfig

#TODO this doesn't change much or ever
echo " --- configuring vim ---"
ln -sf $DOT_DIR/vim/vimrc $HOME/.vimrc
ln -sf $DOT_DIR/vim/autoload $HOME/.vim/autoload
ln -sf $DOT_DIR/vim/colors $HOME/.vim/colors

echo " --- done ---"
