#!/bin/bash

############
# Setup
############

# Use vim key bindings in bash
set -o vi

############
# Source
############

source $HOME/.shell/*
source $DOT_DIR/bash/*.bash

############
# Variables
############

# Add data and time to history
export HISTTIMEFORMAT="%d/%m/%y %T "

# Ignore duplicates and commands that start with whitespace
export HISTCONTROL=ignoreboth

# Set history file size
export HISTSIZE=100

# Add color matches to grep by default
export GREP_OPTIONS="--color=auto"

#TODO: figure out termcap color options
# Add color options to less
#export LESS="--RAW-CONTROL-CHARS"
#[[ -f ~/.LESS_TERMCAP ]] && . ~/.LESS_TERMCAP

############
# History
############

# Review commands with history expansion before executing
shopt -s histverify

# Append to the history file instead of overwriting it
shopt -s histappend

# Allow editing of failed substitutions
shopt -s histreedit

# Set history file location
export HISTFILE=$HOME/.shell/.bash_history

##########
# Import custom bashrc
##########
if [ -f $HOME/.bashrc_original ]; then
  source $HOME/.bashrc_original
fi
