# TODO: zsh color scheme

source $HOME/.shell/profile

# === Antigen ===
export ZPLUG_HOME=~/.zplug
if [ ! -d $ZPLUG_HOME/ ]; then
    curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
fi

source $ZPLUG_HOME/init.zsh
zplug "rupa/z", use:z.sh
zplug "spaceship-prompt/spaceship-prompt", use:spaceship.zsh, from:github, as:theme
zplug "zsh-users/zsh-syntax-highlighting", defer:2
zplug load 

if ! zplug check --verbose; then
    zplug install
fi

# === Options ===
set -o vi

setopt CORRECT
setopt HIST_IGNORE_DUPS
setopt EXTENDED_HISTORY
setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_SPACE
setopt HIST_VERIFY
setopt SHARE_HISTORY

HISTSIZE=100000
SAVEHIST=100000
HISTFILE=$HOME/.shell/.zsh_history
ZDOTDIR=$DOT_DIR/zsh

# === Source ===
source <(fzf --zsh)
for file in $DOT_DIR/zsh/*.zsh; do
    source $file
done
